// Copyright 2004-2006 Adobe Macromedia Software LLC and its licensors. All rights reserved.

MM.HELP_mnuCFUsing = "CF_USING_INDEX";
MM.HELP_mnuDWHelp = "JSH_mnuDWUsing";
MM.HELP_mnuCTHelp = "CON_USING_INDEX";
MM.HELP_mnuDWExtending = "DW_EXTENDING_INDEX";
MM.HELP_mnuDWAPI = "DW_API_INDEX";
MM.HELP_mnuDWGettingStarted = "JSH_mnuDWGettingStarted"; // Getting Started help menu entry
MM.HELP_mnuDWUsing = "JSH_mnuDWUsing"; // Using DW Menu ID
MM.HELP_mnuDWWhatsNew = "JSH_mnuDWWhatsNew"; // Whats new menu entry
MM.HELP_customizeFavorites = "JSH_customizeFavorites"; 
MM.HELP_objAcronym = "JSH_objAcronym"; 
MM.HELP_objAbbreviation = "JSH_objAbbreviation"; 
MM.HELP_cmdKeyboardShortcuts = "JSH_cmdKeyboardShortcuts"; 
MM.HELP_cmdCleanUpWordHTML = "JSH_cmdCleanUpWordHTML"; 
MM.HELP_cmdImportWordHTML = "JSH_cmdImportWordHTML"; 
MM.HELP_recentlyModifiedMC = "JSH_recentlyModifiedMC"; 
MM.HELP_cmdDesignNotes = "JSH_cmdDesignNotes"; 
MM.HELP_recentlyModifiedReport = "JSH_recentlyModifiedReport"; 
MM.HELP_objDiv = "JSH_objDiv"; 
MM.HELP_mnuEditGuides = "JSH_mnuEditGuides"; // Guides dialog
MM.HELP_mnuExplodedModeIntro = "JSH_mnuExplodedModeIntro"; 
MM.HELP_objTable = "JSH_objTable"; 
MM.HELP_objTabularData = "JSH_objTabularData"; // stored in Commands
MM.HELP_cmdFormatTable = "JSH_cmdFormatTable"; 
MM.HELP_cmdSortTable = "JSH_cmdSortTable"; 
MM.HELP_cmdExportTable = "JSH_cmdExportTable"; 
MM.HELP_mnuLayoutViewIntro = "JSH_mnuLayoutViewIntro"; 
MM.HELP_objFrameAccessOptions = "JSH_objFrameAccessOptions"; // frames accessibility dialog
MM.HELP_inspEditableContent = "JSH_inspEditableContent"; // editable region PI
MM.HELP_inspOptionalContent = "JSH_inspOptionalContent"; 
MM.HELP_editableTagAttributes = "JSH_editableTagAttributes"; 
MM.HELP_templateProperties = "JSH_templateProperties"; 
MM.HELP_insertEditableRegion = "JSH_insertEditableRegion"; 
MM.HELP_insertRepeatingContent = "JSH_insertRepeatingContent"; 
MM.HELP_objRepeatingTable = "JSH_objRepeatingTable"; 
MM.HELP_insertOptionalContent = "JSH_insertOptionalContent"; 
MM.HELP_orphanedTemplateContent = "JSH_orphanedTemplateContent"; 
MM.HELP_editableTagAttributes = "JSH_editableTagAttributes"; 
MM.HELP_extractTemplateXML = "JSH_extractTemplateXML"; 
MM.HELP_templateDescription = "JSH_templateDescription"; // Template Description dialog
MM.HELP_cmdSetColorScheme = "JSH_cmdSetColorScheme"; 
MM.HELP_objDate = "JSH_objDate"; // stored in Commands
MM.HELP_inspDate = "JSH_inspDate"; 
MM.HELP_objInsertEntity = "JSH_objInsertEntity"; // stored in Commands
MM.HELP_cmdDesignTimeCSS = "JSH_cmdDesignTimeCSS"; 
MM.HELP_objDropOffice = "JSH_objDropOffice"; 
MM.HELP_objImageAccessOptions = "JSH_objImageAccessOptions"; // image accessibility dialog
MM.HELP_objImgPlaceholder = "JSH_objImgPlaceholder"; 
MM.HELP_objRolloverImage = "JSH_objRolloverImage"; // stored in Commands
MM.HELP_objAnchor = "JSH_objAnchor"; 
MM.HELP_objHyperlink = "JSH_objHyperlink"; // insert hyperlink
MM.HELP_objEMailLink = "JSH_objEMailLink"; 
MM.HELP_objJumpMenu = "JSH_objJumpMenu"; // stored in Commands
MM.HELP_objNavBar = "JSH_objNavBar"; // stored in Commands
MM.HELP_cmdModifyNavBar = "JSH_cmdModifyNavBar"; 
MM.HELP_objFireworksHTML = "JSH_objFireworksHTML"; 
MM.HELP_cmdCreateWebPhotoAlbum = "JSH_cmdCreateWebPhotoAlbum"; 
MM.HELP_FlashVideo_PI = "JSH_FlashVideo_PI"; 
MM.HELP_objFlashVideo = "JSH_objFlashVideo"; 
MM.HELP_objFlashAccessOptions = "JSH_objFlashAccessOptions"; // flash button and flash text dialog
MM.HELP_objObjectAccessOptionsdialog = "JSH_objObjectAccessOptionsdialog"; // generator, flash, activex, shockwave attributes dialog
MM.HELP_behCallJavaScript = "JSH_behCallJavaScript"; 
MM.HELP_behChangeProperty = "JSH_behChangeProperty"; 
MM.HELP_behCheckBrowser = "JSH_behCheckBrowser"; 
MM.HELP_behCheckPlugin = "JSH_behCheckPlugin"; 
MM.HELP_behControlShockwave = "JSH_behControlShockwave"; 
MM.HELP_behDragLayer = "JSH_behDragLayer"; 
MM.HELP_behGoToURL = "JSH_behGoToURL"; 
MM.HELP_behJumpMenu = "JSH_behJumpMenu"; 
MM.HELP_behJumpMenuGo = "JSH_behJumpMenuGo"; 
MM.HELP_behOpenBrowserWindow = "JSH_behOpenBrowserWindow"; 
MM.HELP_behPlaySound = "JSH_behPlaySound"; 
MM.HELP_behPopupMessage = "JSH_behPopupMessage"; 
MM.HELP_behPreloadImages = "JSH_behPreloadImages"; 
MM.HELP_behSetNavBarImage = "JSH_behSetNavBarImage"; 
MM.HELP_behSetTextOfFrame = "JSH_behSetTextOfFrame"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfLayer = "JSH_behSetTextOfLayer"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfStatusBar = "JSH_behSetTextOfStatusBar"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfTextField = "JSH_behSetTextOfTextField"; // stored in sub-folder Set Text
MM.HELP_behShowHideLayers = "JSH_behShowHideLayers"; 
MM.HELP_behShowPopupMenu = "JSH_behShowPopupMenu"; 
MM.HELP_behHidePopupMenu = "JSH_behHidePopupMenu"; 
MM.HELP_behSwapImage = "JSH_behSwapImage"; 
MM.HELP_behSwapImageRestore = "JSH_behSwapImageRestore"; 
MM.HELP_behValidateForm = "JSH_behValidateForm"; 
MM.HELP_behEffectAppearFade = "JSH_behEffectAppearFade"; // AppearFade Effect dialog
MM.HELP_behEffectBlind = "JSH_behEffectBlind"; // Blind Effect dialog
MM.HELP_behEffectGrowShrink = "JSH_behEffectGrowShrink"; // GrowShrink Effect dialog
MM.HELP_behEffectHighlight = "JSH_behEffectHighlight"; // Highlight Effect dialog
MM.HELP_behEffectShake = "JSH_behEffectShake"; // Shake Effect dialog
MM.HELP_behEffectSlide = "JSH_behEffectSlide"; // Slide Effect dialog
MM.HELP_behEffectSquish = "JSH_behEffectSquish"; // Squish Effect dialog
MM.HELP_FW8PopupMenus = "JSH_FW8PopupMenus"; // Show popup menu help topic
MM.HELP_dtdImport = "JSH_dtdImport"; 
MM.HELP_aspnetImportSelected = "JSH_aspnetImportSelected"; 
MM.HELP_newTags = "JSH_newTags"; 
MM.HELP_newAttributes = "JSH_newAttributes"; 
MM.HELP_tiImportTLDFile = "JSH_tiImportTLDFile"; 
MM.HELP_cmdtiImportWebXML = "JSH_cmdtiImportWebXML"; 
MM.HELP_tiImportTLDFolder = "JSH_tiImportTLDFolder"; 
MM.HELP_objComment = "JSH_objComment"; 
MM.HELP_cmdCleanUpHTML = "JSH_cmdCleanUpHTML"; 
MM.HELP_objScript = "JSH_objScript"; 
MM.HELP_inspSsiCommon = "JSH_inspSsiCommon"; 
MM.HELP_objMeta = "JSH_objMeta"; 
MM.HELP_inspMeta = "JSH_inspMeta"; 
MM.HELP_inspTitle = "JSH_inspTitle"; 
MM.HELP_objKeywords = "JSH_objKeywords"; 
MM.HELP_inspKeywords = "JSH_inspKeywords"; 
MM.HELP_objDescription = "JSH_objDescription"; 
MM.HELP_inspDescription = "JSH_inspDescription"; 
MM.HELP_objRefresh = "JSH_objRefresh"; 
MM.HELP_inspRefresh = "JSH_inspRefresh"; 
MM.HELP_objBase = "JSH_objBase"; 
MM.HELP_inspBase = "JSH_inspBase"; 
MM.HELP_objLink = "JSH_objLink"; 
MM.HELP_inspLink = "JSH_inspLink"; 
MM.HELP_inspGeneric = "JSH_inspGeneric"; // generic PI
MM.HELP_DSsettingDB2 = "JSH_DSsettingDB2"; 
MM.HELP_DSsettingInformix = "JSH_DSsettingInformix"; 
MM.HELP_DSsettingMSAccess = "JSH_DSsettingMSAccess"; 
MM.HELP_DSsettingMSAccessUnicode = "JSH_DSsettingMSAccessUnicode"; 
MM.HELP_DSsettingMSSQL = "JSH_DSsettingMSSQL"; 
MM.HELP_DSsettingMySQL = "JSH_DSsettingMySQL"; 
MM.HELP_DSsettingODBC = "JSH_DSsettingODBC"; 
MM.HELP_DSsettingOracle = "JSH_DSsettingOracle"; 
MM.HELP_DSsettingOther = "JSH_DSsettingOther"; 
MM.HELP_DSsettingSybase = "JSH_DSsettingSybase"; 
MM.HELP_connASPNETOleDb = "JSH_connASPNETOleDb"; 
MM.HELP_connASPNETOleDbTemplate = "JSH_connASPNETOleDbTemplate"; 
MM.HELP_connASPNETSqlServer = "JSH_connASPNETSqlServer"; 
MM.HELP_connASPDSN = "JSH_connASPDSN"; 
MM.HELP_cmdSelectDSNList = "JSH_cmdSelectDSNList"; 
MM.HELP_connASPConnString = "JSH_connASPConnString"; 
MM.HELP_connJSP = "JSH_connJSP"; 
MM.HELP_connPHP = "JSH_connPHP"; // MySQL Connection dialog
MM.HELP_cmdSelectPHPDSNList = "JSH_cmdSelectPHPDSNList"; 
MM.HELP_compJavaBeans = "JSH_compJavaBeans"; // JavaBeans view of Components panel
MM.HELP_ssURLVariable = "JSH_ssURLVariable"; 
MM.HELP_ssFormVariable = "JSH_ssFormVariable"; 
MM.HELP_dataSourceNameVariable = "JSH_dataSourceNameVariable"; // Data Source Name Variable
MM.HELP_ssCookieVariable = "JSH_ssCookieVariable"; 
MM.HELP_ssServerVariable = "JSH_ssServerVariable"; 
MM.HELP_ssEnvironmentVariable = "JSH_ssEnvironmentVariable"; 
MM.HELP_ssDynamicBinding = "JSH_ssDynamicBinding"; 
MM.HELP_ssSimpleRecordset = "JSH_ssSimpleRecordset"; 
MM.HELP_ssCFSimpleRecordset = "JSH_ssCFSimpleRecordset"; // Simple Recordset ColdFusion
MM.HELP_cmdcfDataSourceLogin = "JSH_cmdcfDataSourceLogin"; // Data Source Login
MM.HELP_sbASPNetSimpleRecordset = "JSH_sbASPNetSimpleRecordset"; 
MM.HELP_ssAdvancedRecordset = "JSH_ssAdvancedRecordset"; 
MM.HELP_sbASPNetAdvRecordset = "JSH_sbASPNetAdvRecordset"; 
MM.HELP_ssCFAdvancedRecordset = "JSH_ssCFAdvancedRecordset"; 
MM.HELP_ssRequestVariable = "JSH_ssRequestVariable"; 
MM.HELP_cmdASPNetAddParam = "JSH_cmdASPNetAddParam"; 
MM.HELP_cmdCFAddParam = "JSH_cmdCFAddParam"; 
MM.HELP_cmdASPNetAddParam = "JSH_cmdASPNetAddParam"; 
MM.HELP_cmdPHPAddParam = "JSH_cmdPHPAddParam"; 
MM.HELP_ssJSPRequestVariable = "JSH_ssJSPRequestVariable"; 
MM.HELP_ssCFSessionVariable = "JSH_ssCFSessionVariable"; 
MM.HELP_ssSessionVariable = "JSH_ssSessionVariable"; 
MM.HELP_ssApplicationVariable = "JSH_ssApplicationVariable"; 
MM.HELP_ssCFApplicationVariable = "JSH_ssCFApplicationVariable"; 
MM.HELP_ssCFURLVariable = "JSH_ssCFURLVariable"; 
MM.HELP_ssCFFormVariable = "JSH_ssCFFormVariable"; 
MM.HELP_ssCFClientVariable = "JSH_ssCFClientVariable"; 
MM.HELP_ssCFCookieVariable = "JSH_ssCFCookieVariable"; 
MM.HELP_ssCFCGIVariable = "JSH_ssCFCGIVariable"; 
MM.HELP_ssCFServerVariable = "JSH_ssCFServerVariable"; 
MM.HELP_ssCFVariablesVariable = "JSH_ssCFVariablesVariable"; 
MM.HELP_inspRecordset = "JSH_inspRecordset"; 
MM.HELP_inspStoredProcedure = "JSH_inspStoredProcedure"; 
MM.HELP_inspJspPrepared = "JSH_inspJspPrepared"; 
MM.HELP_inspRepeatedRegion = "JSH_inspRepeatedRegion"; 
MM.HELP_ssHideRegion = "JSH_ssHideRegion"; // various Show Region SBs
MM.HELP_objDynamicTable = "JSH_objDynamicTable"; 
MM.HELP_sbRSStatsFirst = "JSH_sbRSStatsFirst"; // Display Starting Record Number
MM.HELP_sbRSStatsLast = "JSH_sbRSStatsLast"; // Display Ending Record Number
MM.HELP_sbRSStatsTotal = "JSH_sbRSStatsTotal"; // Display Total Records
MM.HELP_objRecordsetNavigation = "JSH_objRecordsetNavigation"; 
MM.HELP_ssMoveTo = "JSH_ssMoveTo"; 
MM.HELP_ssRepeatedRegion = "JSH_ssRepeatedRegion"; 
MM.HELP_objRecordsetStatistics = "JSH_objRecordsetStatistics"; 
MM.HELP_fmt_ASP_Currency = "JSH_fmt_ASP_Currency"; 
MM.HELP_fmt_JSP_Currency = "JSH_fmt_JSP_Currency"; 
MM.HELP_fmt_JSP_Number = "JSH_fmt_JSP_Number"; 
MM.HELP_fmt_ASP_Number = "JSH_fmt_ASP_Number"; 
MM.HELP_fmt_ASP_Percent = "JSH_fmt_ASP_Percent"; 
MM.HELP_fmt_JSP_Percent = "JSH_fmt_JSP_Percent"; 
MM.HELP_ssRSStatsCurrentPage = "JSH_ssRSStatsCurrentPage"; // Display Current Page Number
MM.HELP_ConfigureXSLTransform = "JSH_ConfigureXSLTransform"; 
MM.HELP_cmdXSLTAddParam = "JSH_cmdXSLTAddParam"; 
MM.HELP_objXSLTComment = "JSH_objXSLTComment"; // Comment dialog
MM.HELP_cmdAttachXSLT = "JSH_cmdAttachXSLT"; // Attach XSLT Stylesheet
MM.HELP_objXSLTIf = "JSH_objXSLTIf"; // XSL Conditional Region dialog
MM.HELP_objXSLTChoose = "JSH_objXSLTChoose"; // XSL Multiple Condition dialog
MM.HELP_inspXSLForEach = "JSH_inspXSLForEach"; // XSL Repeat Region PI
MM.HELP_inspXSLIf = "JSH_inspXSLIf"; // XSL Conditional Region PI
MM.HELP_inspXSLChoose = "JSH_inspXSLChoose"; // XSL Multiple Condition PI
MM.HELP_cmdDeclMissingEntities = "JSH_cmdDeclMissingEntities"; // Missing Entity message box
MM.HELP_compWebServices = "JSH_compWebServices"; 
MM.HELP_wsDefaultProxyGen = "JSH_wsDefaultProxyGen"; 
MM.HELP_ssServerModelList = "JSH_ssServerModelList"; 
MM.HELP_wsCF6ProxyGen = "JSH_wsCF6ProxyGen"; // ColdFusion 6 Proxy Generator (JavaScript)
MM.HELP_ssProxyChooser = "JSH_ssProxyChooser"; 
MM.HELP_wsProxyGenUsingIntrospector = "JSH_wsProxyGenUsingIntrospector"; 
MM.HELP_objFormAccessOptions = "JSH_objFormAccessOptions"; // form objects accessibility dialog
MM.HELP_RadioGroup = "JSH_RadioGroup"; 
MM.HELP_CheckboxGroup = "JSH_CheckboxGroup";
MM.HELP_ssDynamicRadioGroupCF = "JSH_ssDynamicRadioGroupCF"; // Dynamic Radio Group (ColdFusion)
MM.HELP_ssDynamicRadioGroupASPNet = "JSH_ssDynamicRadioGroupASPNet"; // Dynamic Radio Group (ASP.NET)
MM.HELP_ssDynamicRadioGroup = "JSH_ssDynamicRadioGroup"; // Dynamic Radio Group dialog box
MM.HELP_ssDynamicTextField = "JSH_ssDynamicTextField"; 
MM.HELP_ssDynamicCheckBox = "JSH_ssDynamicCheckBox"; 
MM.HELP_ssDynamicSelectList = "JSH_ssDynamicSelectList"; 
MM.HELP_settingCFformProperties_PI = "JSH_settingCFformProperties_PI"; 
MM.HELP_settingCFtextfieldProperties_PI = "JSH_settingCFtextfieldProperties_PI"; 
MM.HELP_settingCFhiddenfieldProperties_PI = "JSH_settingCFhiddenfieldProperties_PI"; 
MM.HELP_settingCFtextareaProperties_PI = "JSH_settingCFtextareaProperties_PI"; 
MM.HELP_settingCFbuttonProperties_PI = "JSH_settingCFbuttonProperties_PI"; 
MM.HELP_settingCFcheckboxProperties_PI = "JSH_settingCFcheckboxProperties_PI"; 
MM.HELP_settingCFradiobuttonProperties_PI = "JSH_settingCFradiobuttonProperties_PI"; 
MM.HELP_settingCFselectProperties_PI = "JSH_settingCFselectProperties_PI"; 
MM.HELP_settingCFimagefieldProperties_PI = "JSH_settingCFimagefieldProperties_PI"; 
MM.HELP_settingCFfilefieldProperties_PI = "JSH_settingCFfilefieldProperties_PI"; 
MM.HELP_settingCFdatefieldProperties_PI = "JSH_settingCFdatefieldProperties_PI"; 
MM.HELP_objMasterDetail = "JSH_objMasterDetail"; 
MM.HELP_cmdCFAddColumn = "JSH_cmdCFAddColumn"; 
MM.HELP_objInsertRecord = "JSH_objInsertRecord"; 
MM.HELP_soASPNetInsertForm = "JSH_soASPNetInsertForm"; 
MM.HELP_soFormFieldProps = "JSH_soFormFieldProps"; 
MM.HELP_ssInsertRecord = "JSH_ssInsertRecord"; 
MM.HELP_sbPHPInsertRecord = "JSH_sbPHPInsertRecord"; // insert record PHP
MM.HELP_sbCFInsertRecord = "JSH_sbCFInsertRecord"; // insert record coldfusion
MM.HELP_sbASPNetInsertRecord = "JSH_sbASPNetInsertRecord"; 
MM.HELP_objUpdateRecord = "JSH_objUpdateRecord"; 
MM.HELP_sbCFUpdateRecord = "JSH_sbCFUpdateRecord"; // update record coldfusion
MM.HELP_sbCFDeleteRecord = "JSH_sbCFDeleteRecord"; // delete record coldfusion
MM.HELP_ssCFStoredProc = "JSH_ssCFStoredProc"; // coldfusion mx stored procedure
MM.HELP_cmdCFAddStoredProcVar = "JSH_cmdCFAddStoredProcVar"; // add/edit stored procedure variable
MM.HELP_sbCheckNewUsername = "JSH_sbCheckNewUsername"; 
MM.HELP_sbLoginUser = "JSH_sbLoginUser"; 
MM.HELP_sbRestrictAccessToPage = "JSH_sbRestrictAccessToPage"; 
MM.HELP_sbDefineAccessLevels = "JSH_sbDefineAccessLevels"; 
MM.HELP_sbLogoutUser = "JSH_sbLogoutUser"; 
MM.HELP_CFLoginWizard_cmd = "JSH_CFLoginWizard_cmd"; 
MM.HELP_cmdCreateComponent = "JSH_cmdCreateComponent"; 
MM.HELP_compCFCs = "JSH_compCFCs"; // CFC view of Components panel
MM.HELP_CFCQuery_cmd = "JSH_CFCQuery_cmd"; 
MM.HELP_newCFC = "JSH_newCFC"; 
MM.HELP_editParam_cmd = "JSH_editParam_cmd"; 
MM.HELP_objASPNETButton = "JSH_objASPNETButton"; 
MM.HELP_objASPNETCheckBox = "JSH_objASPNETCheckBox"; 
MM.HELP_objASPNETImageButton = "JSH_objASPNETImageButton"; 
MM.HELP_objASPNETLabel = "JSH_objASPNETLabel"; 
MM.HELP_objASPNETRadioButton = "JSH_objASPNETRadioButton"; 
MM.HELP_objASPNETTextBox = "JSH_objASPNETTextBox"; 
MM.HELP_objASPNETCheckBoxList = "JSH_objASPNETCheckBoxList"; 
MM.HELP_objASPNETDropDownList = "JSH_objASPNETDropDownList"; 
MM.HELP_objASPNETListBox = "JSH_objASPNETListBox"; 
MM.HELP_objASPNETRadioButtonList = "JSH_objASPNETRadioButtonList"; 
MM.HELP_piASPNETButton = "JSH_piASPNETButton"; 
MM.HELP_piASPNETCheckBox = "JSH_piASPNETCheckBox"; 
MM.HELP_piASPNETImageButton = "JSH_piASPNETImageButton"; 
MM.HELP_piASPNETLabel = "JSH_piASPNETLabel"; 
MM.HELP_piASPNETRadioButton = "JSH_piASPNETRadioButton"; 
MM.HELP_piASPNETTextBox = "JSH_piASPNETTextBox"; 
MM.HELP_piASPNETCheckBoxList = "JSH_piASPNETCheckBoxList"; 
MM.HELP_piASPNETDropDownList = "JSH_piASPNETDropDownList"; 
MM.HELP_piASPNETListBox = "JSH_piASPNETListBox"; 
MM.HELP_piASPNETRadioButtonList = "JSH_piASPNETRadioButtonList"; 
MM.HELP_soMenuProps = "JSH_soMenuProps"; 
MM.HELP_ssDataGridAspNet = "JSH_ssDataGridAspNet"; 
MM.HELP_sbASPNetDataGridBound = "JSH_sbASPNetDataGridBound"; 
MM.HELP_sbASPNetDataGridTemplate = "JSH_sbASPNetDataGridTemplate"; 
MM.HELP_sbASPNetDataGridHyperlink = "JSH_sbASPNetDataGridHyperlink"; 
MM.HELP_sbASPNetDataGridEdit = "JSH_sbASPNetDataGridEdit"; 
MM.HELP_sbASPNetDataGridDelete = "JSH_sbASPNetDataGridDelete"; 
MM.HELP_ssDataListAspNet = "JSH_ssDataListAspNet"; 
MM.HELP_ssAddDataFieldDlgAspNet = "JSH_ssAddDataFieldDlgAspNet"; 
MM.HELP_piDataGridAspNet = "JSH_piDataGridAspNet"; 
MM.HELP_piDataListAspNet = "JSH_piDataListAspNet"; 
MM.HELP_soASPNetUpdateForm = "JSH_soASPNetUpdateForm"; 
MM.HELP_sbASPNetUpdateRecord = "JSH_sbASPNetUpdateRecord"; 
MM.HELP_sbASPNetDeleteRecord = "JSH_sbASPNetDeleteRecord"; 
MM.HELP_sbASPNetStoredProc = "JSH_sbASPNetStoredProc"; 
MM.HELP_cmdASPNetSprocParam = "JSH_cmdASPNetSprocParam"; 
MM.HELP_cmdASPNetBuildRuntime = "JSH_cmdASPNetBuildRuntime"; 
MM.HELP_ssGoToDetailPage = "JSH_ssGoToDetailPage"; 
MM.HELP_ssMoveToSpecificRecord = "JSH_ssMoveToSpecificRecord"; 
MM.HELP_ssGoToRelatedPage = "JSH_ssGoToRelatedPage"; 
MM.HELP_ssUpdateRecord = "JSH_ssUpdateRecord"; 
MM.HELP_ssDeleteRecord = "JSH_ssDeleteRecord"; 
MM.HELP_ssCommandAsp = "JSH_ssCommandAsp"; 
MM.HELP_ssCallableJsp = "JSH_ssCallableJsp"; 
MM.HELP_ssPreparedJsp = "JSH_ssPreparedJsp"; 
MM.HELP_ssJavaBean = "JSH_ssJavaBean"; 
MM.HELP_ssJavaBeanIndexed = "JSH_ssJavaBeanIndexed"; 
MM.HELP_sbPHPUpdateRecord = "JSH_sbPHPUpdateRecord"; // update record PHP
MM.HELP_sbPHPDeleteRecord = "JSH_sbPHPDeleteRecord"; // delete record PHP
MM.HELP_cfSelectListValues = "JSH_cfSelectListValues"; 
MM.HELP_objSpryMenuBar = "JSH_objSpryMenuBar";
MM.HELP_piAccordion = "JSH_piAccordion";
MM.HELP_piMenuBar = "JSH_piMenuBar";
MM.HELP_piTabbedPanels = "JSH_piTabbedPanels";
MM.HELP_piCollapsiblePanel = "JSH_piCollapsiblePanel";
MM.HELP_piValidationTextField = "JSH_piValidationTextField";
MM.HELP_piValidationTextarea = "JSH_piValidationTextarea";
MM.HELP_piValidationSelect = "JSH_piValidationSelect";
MM.HELP_piValidationCheckbox = "JSH_piValidationCheckbox";
MM.HELP_piAccordionGuide = "JSH_piAccordionGuide";
MM.HELP_piMenuBarGuide = "JSH_piMenuBarGuide";
MM.HELP_piTabbedPanelsGuide = "JSH_piTabbedPanelsGuide";
MM.HELP_piCollapsiblePanelGuide = "JSH_piCollapsiblePanelGuide";
MM.HELP_piValidationTextFieldGuide = "JSH_piValidationTextFieldGuide";
MM.HELP_piValidationTextareaGuide = "JSH_piValidationTextareaGuide";
MM.HELP_piValidationSelectGuide = "JSH_piValidationSelectGuide";
MM.HELP_piValidationCheckboxGuide = "JSH_piValidationCheckboxGuide";
MM.HELP_cmdSpryDataSetXML = "JSH_cmdSpryDataSetXML";
MM.HELP_cmdSpryDataSetHTML = "JSH_cmdSpryDataSetHTML";
MM.HELP_cmdSpryDSAdvancedSelection = "JSH_cmdSpryDSAdvancedSelection";
MM.HELP_cmdSpryDesignTimeFeed = "JSH_cmdSpryDesignTimeFeed";
MM.HELP_objSpryRegion = "JSH_objSpryRegion";
MM.HELP_objSpryRepeat = "JSH_objSpryRepeat";
MM.HELP_objSpryRepeatList = "JSH_objSpryRepeatList";
MM.HELP_objSpryDataTable = "JSH_objSpryDataTable";
MM.HELP_objSprySpotlightColumn  = "JSH_objSprySpotlightColumn";
MM.HELP_objSpryMasterDetail  = "JSH_objSpryMasterDetail";
MM.HELP_objSpryStackedContainers  = "JSH_objSpryStackedContainers";
MM.HELP_cmdExternalizeJavaScript  = "JSH_cmdExternalizeJavaScript";
MM.HELP_piValidationPassword = "JSH_piValidationPassword";
MM.HELP_piValidationPasswordGuide = "JSH_piValidationPasswordGuide";
MM.HELP_piValidationConfirm = "JSH_piValidationConfirm";
MM.HELP_piValidationConfirmGuide = "JSH_piValidationConfirmGuide";
MM.HELP_objSpryValidationRadio = "JSH_objSpryValidationRadio";
MM.HELP_piValidationRadio = "JSH_piValidationRadio";
MM.HELP_piValidationRadioGuide = "JSH_piValidationRadioGuide";
MM.HELP_piTooltip = "JSH_piTooltip";        
MM.HELP_piTooltipGuide = "JSH_piTooltipGuide";
MM.HELP_cmdBrowserAddress = "JSH_cmdBrowserAddress";
MM.HELP_objInsertWidget = "JSH_objInsertWidget";
MM.HELP_cmdSiteSpecificCodeHints = "JSH_cmdSiteSpecificCodeHints";
MM.HELP_html5css3 = "HELP_HTML5_CSS3";
MM.HELP_cmdMediaQueryMngr = "JSH_cmdMediaQueryMngr";
MM.HELP_cmdNativeAppFrameworkSetup = "JSH_cmdNativeAppFrameworkSetup";
MM.HELP_cmdNativeAppSetup = "JSH_cmdNativeAppSetup";
MM.HELP_phoneGapBuildService = "JSH_pgbServicePanel";
MM.HELP_phoneGapBuildServiceSettings = "JSH_pgbSettingsPanel";
MM.HELP_jQueryMobile = "JSH_jQueryMobile";
MM.HELP_fluidGrid = "HELP_fluidGrid";
MM.HELP_bcPanel = "JSH_bcPanel";
MM.HELP_bcCreateSite = "JSH_bcCreateSite";
MM.HELP_bcImportSite = "JSH_bcImportSite";
MM.HELP_jQuerySwatches = "JSH_jQuerySwatches";
