// Copyright 2001-2006 Adobe Macromedia Software LLC and its licensors. All rights reserved.
/* loc_strings.js
*
* strings.js and loc_strings.js contain arrays for populating select lists 
* in tag dialogs. Both files use the naming convention arrayNameCap for the
* option labels (i.e., text that will be shown to the user) and arrayNameVal
* for the option values(i.e., the code that will be inserted into the document).
* 
* for obvious reasons, loc_strings.js mainly contains the Cap arrays, and
* strings.js mainly contains the Val arrays. only loc_strings.js should be
* localized.  
*
* note: where the labels should not be localized, select lists are intialized
* using the Val array for both the labels and the values.
* 
*/

//--------------- LOCALIZEABLE GLOBALS---------------

var theLookAndFeelCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLookAndFeelCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLookAndFeelCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theLookAndFeelCap_2'));
var theSubmissionMethodsCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSubmissionMethodsCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSubmissionMethodsCap_1'));
var theLoginStorageCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLoginStorageCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLoginStorageCap_1'));
var theVericalAlignmentsCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theVericalAlignmentsCap_8'));
var theAlignmentsCatchCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsCatchCap_8'));
var theAlignmentsColCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsColCap'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsColCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theAlignmentsColCap_2'));
var theTypesContentCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_12'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_13'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_14'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_15'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_16'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_17'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_18'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_19'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_20'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_21'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_22'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_23'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_24'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_25'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_26'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesContentCap_27'));






var theExpiresCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theExpiresCap'),dw.loadString('TagLibraries/CFML/loc_strings/theExpiresCap_1'));
var theLanCollectionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_12'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_13'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_14'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_15'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_16'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_17'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_18'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_19'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_20'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_21'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_22'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_23'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_24'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_25'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_26'),dw.loadString('TagLibraries/CFML/loc_strings/theLanCollectionCap_27'));
var theSelCollectionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCollectionCap_6'));
var theSelDirectoryCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelDirectoryCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelDirectoryCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelDirectoryCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelDirectoryCap_3'));
var theSelFileCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFileCap_8'));
var theFileNameConflictCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theFileNameConflictCap'),dw.loadString('TagLibraries/CFML/loc_strings/theFileNameConflictCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theFileNameConflictCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theFileNameConflictCap_3'));
var theSelectModeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelectModeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelectModeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelectModeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelectModeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSelectModeCap_4'));
var theGridDataAlignCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theGridDataAlignCap'),dw.loadString('TagLibraries/CFML/loc_strings/theGridDataAlignCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theGridDataAlignCap_2'));
var theGridColTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theGridColTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theGridColTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theGridColTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theGridColTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theGridColTypeCap_4'));
var theSelHeaderCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelHeaderCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelHeaderCap_1'));
var theSelCalendarCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelCalendarCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCalendarCap_1'));
var theSelInvokeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelInvokeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelInvokeCap_1'));
var theHTTPMethodCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPMethodCap_6'));
var theHTTPPARAMTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theHTTPPARAMTypeCap_7'));
var theTransactionActionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTransactionActionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTransactionActionCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTransactionActionCap_2'));
var theObjectActionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theObjectActionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theObjectActionCap_1'));
var theObjectCOMContextCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theObjectCOMContextCap'),dw.loadString('TagLibraries/CFML/loc_strings/theObjectCOMContextCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theObjectCOMContextCap_2'));
var theObjectCORBAContextCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theObjectCORBAContextCap'),dw.loadString('TagLibraries/CFML/loc_strings/theObjectCORBAContextCap_1'));
var theSelObjectCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelObjectCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelObjectCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelObjectCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelObjectCap_3'));
var theSearchTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSearchTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSearchTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSearchTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSearchTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSearchTypeCap_4'));
var theServletparamTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theServletparamTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theServletparamTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theServletparamTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theServletparamTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theServletparamTypeCap_4'));

var theRegistryGetSetTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetSetTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetSetTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetSetTypeCap_2'));
var theRegistryGetAllTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetAllTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetAllTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetAllTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theRegistryGetAllTypeCap_3'));

var theParamTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_12'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_13'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_14'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_15'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_16'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_17'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_18'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_19'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_20'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_21'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_22'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_23'),dw.loadString('TagLibraries/CFML/loc_strings/theParamTypeCap_24'));
var theLockTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLockTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLockTypeCap_1'));
var theLockScopeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLockScopeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLockScopeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theLockScopeCap_2'));
var theProcparamTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theProcparamTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theProcparamTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theProcparamTypeCap_2'));
var theSelMailparamCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelMailparamCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelMailparamCap_1'));
var theIndexTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theIndexTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theIndexTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theIndexTypeCap_2'));
var theSelIndexCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelIndexCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelIndexCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelIndexCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelIndexCap_3'));
var theSelInputCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelInputCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelInputCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelInputCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelInputCap_3'));
var theTextInputValidateCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theTextInputValidateCap_8'));
var theInputValidateCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_12'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_13'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_14'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_15'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_16'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_17'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_18'),dw.loadString('TagLibraries/CFML/loc_strings/theInputValidateCap_19'));
var theMailTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theMailTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theMailTypeCap_1'));
var theMailPartTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theMailPartTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theMailPartTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theMailPartTypeCap_2'));
var theCharSetCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_12'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_13'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_14'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_15'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_16'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_17'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_18'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_19'),dw.loadString('TagLibraries/CFML/loc_strings/theCharSetCap_20'));
var theQueryDBTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theQueryDBTypeCap_8'));
var theSelCacheCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelCacheCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCacheCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCacheCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCacheCap_3'));
var theErrorTypesCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theErrorTypesCap'),dw.loadString('TagLibraries/CFML/loc_strings/theErrorTypesCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theErrorTypesCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theErrorTypesCap_3'));
var theScopeCfldapCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theScopeCfldapCap'),dw.loadString('TagLibraries/CFML/loc_strings/theScopeCfldapCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theScopeCfldapCap_2'));
var theModifyTypeCfldapCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theModifyTypeCfldapCap'),dw.loadString('TagLibraries/CFML/loc_strings/theModifyTypeCfldapCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theModifyTypeCfldapCap_2'));
var theSelCfscheduleCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelCfscheduleCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCfscheduleCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelCfscheduleCap_2'));
var theLogLogCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLogLogCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLogLogCap_1'));
var theTypeLogCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTypeLogCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTypeLogCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTypeLogCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTypeLogCap_3'));
var theSelGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelGraphCap_2'));
var theFileFormatGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theFileFormatGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theFileFormatGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theFileFormatGraphCap_2'));
var theShowValueLabelGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theShowValueLabelGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theShowValueLabelGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theShowValueLabelGraphCap_2'));
var theValueLabelFontGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theValueLabelFontGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theValueLabelFontGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theValueLabelFontGraphCap_2'));
var theItemLabelFontGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theItemLabelFontGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theItemLabelFontGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theItemLabelFontGraphCap_2'));
var theTitleFontGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTitleFontGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTitleFontGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTitleFontGraphCap_2'));
var theShowLegendGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theShowLegendGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theShowLegendGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theShowLegendGraphCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theShowLegendGraphCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theShowLegendGraphCap_4'));
var theValueLocationPieCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theValueLocationPieCap'),dw.loadString('TagLibraries/CFML/loc_strings/theValueLocationPieCap_1'));
var theItemLabelOrientationGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theItemLabelOrientationGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theItemLabelOrientationGraphCap_1'));
var theLegendFontGraphCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theLegendFontGraphCap'),dw.loadString('TagLibraries/CFML/loc_strings/theLegendFontGraphCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theLegendFontGraphCap_2'));
var theGetAsBinaryCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theGetAsBinaryCap'),dw.loadString('TagLibraries/CFML/loc_strings/theGetAsBinaryCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theGetAsBinaryCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theGetAsBinaryCap_3'));
var theReportTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theReportTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theReportTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theReportTypeCap_2'));
var theReportFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theReportFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theReportFormatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theReportFormatCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theReportFormatCap_3'));
var theFormFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theFormFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theFormFormatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theFormFormatCap_2'));
var theGridFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theGridFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theGridFormatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theGridFormatCap_2'));
var theTreeFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTreeFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTreeFormatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTreeFormatCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTreeFormatCap_3'));
var theSkinListCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSkinListCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSkinListCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSkinListCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSkinListCap_3'));
var theXMLSkinListCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theXMLSkinListCap_9'));


// CFC strings to localize
var theTypesCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theTypesCap_12'));
var theAccessCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theAccessCap'),dw.loadString('TagLibraries/CFML/loc_strings/theAccessCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theAccessCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theAccessCap_3'));
var theTraceTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTraceTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTraceTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTraceTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theTraceTypeCap_3'));
var theObjectcacheActionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theObjectcacheActionCap'));
var theChartSeriesTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesTypeCap_10'));
var theChartSeriesPaintStyleCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesPaintStyleCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesPaintStyleCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesPaintStyleCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesPaintStyleCap_3'));

var theChartFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartFormatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theChartFormatCap_2'));
var theChartSeriesplacementCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesplacementCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesplacementCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesplacementCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theChartSeriesplacementCap_3'));
var theChartLabelformatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartLabelformatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartLabelformatCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theChartLabelformatCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theChartLabelformatCap_3'));
var theChartPieSliceStyleCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theChartPieSliceStyleCap'),dw.loadString('TagLibraries/CFML/loc_strings/theChartPieSliceStyleCap_1'));
var theDataLabelStyleCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDataLabelStyleCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDataLabelStyleCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theDataLabelStyleCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theDataLabelStyleCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theDataLabelStyleCap_4'));
var theSelTimerCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelTimerCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelTimerCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelTimerCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelTimerCap_3'));
var theSelDocumentItemCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelDocumentItemCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelDocumentItemCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelDocumentItemCap_2'));
var theSelFormItemCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormItemCap_5'));
var theSelFormGroupCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_8'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_9'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_10'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_11'),dw.loadString('TagLibraries/CFML/loc_strings/theSelFormGroupCap_12'));
var theTextAreaCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theTextAreaCap'),dw.loadString('TagLibraries/CFML/loc_strings/theTextAreaCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theTextAreaCap_2'));
var theDocumentFormatCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentFormatCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentFormatCap_1'));
var theDocumentPageTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_7'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPageTypeCap_8'));
var theDocumentUnitsCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentUnitsCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentUnitsCap_1'));
var theDocumentEncryptionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentEncryptionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentEncryptionCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentEncryptionCap_2'));
var theDocumentPermissionsCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentPermissionsCap_7'));
var theDocumentOrientationCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDocumentOrientationCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDocumentOrientationCap_1'));
var theComponentStyleCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theComponentStyleCap'),dw.loadString('TagLibraries/CFML/loc_strings/theComponentStyleCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theComponentStyleCap_2'));
var theMailparamTypeCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theMailparamTypeCap'),dw.loadString('TagLibraries/CFML/loc_strings/theMailparamTypeCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theMailparamTypeCap_2'));
var theReportPDFEncryptionCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFEncryptionCap'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFEncryptionCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFEncryptionCap_2'));
var theReportPDFPermissionsCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_3'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_4'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_5'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_6'),dw.loadString('TagLibraries/CFML/loc_strings/theReportPDFPermissionsCap_7'));
var theDelimeterCap= new Array(dw.loadString('TagLibraries/CFML/loc_strings/theDelimeterCap'),dw.loadString('TagLibraries/CFML/loc_strings/theDelimeterCap_1'),dw.loadString('TagLibraries/CFML/loc_strings/theDelimeterCap_2'),dw.loadString('TagLibraries/CFML/loc_strings/theDelimeterCap_3'));
//--------------- END LOCALIZEABLE   ---------------
